class ENTfile:
    def __init__(self):
        file = dict()
        file["objects"] = []
        file["scenes"] = []
        file["variables"] = []
        file["messages"] = []
        file["functions"] = []
        file["tables"] = []

        file["speed"] = 60
        file["interface"] = {"canvasWidth": 300, "object": ""} #첫선택 오브젝트
        file["expansionBlocks"] = []
        file["aiUtilizeBlocks"] = []
        file["hardwareLiteBlocks"] = []
        file["externalModules"] = []
        file["externalModulesLite"] = []
        
        file["likeCnt"] = 0
        file["visit"] = 0
        file["isopen"] = True
        file["name"] = "Generated by ScratchEntry"
        file["recentLikeCnt"] = 0
        file["childCnt"] = 0
        file["comment"] = 0

        self._json = file